spring.application.name=app

# -------------------------
# OpenAI Configuration
# -------------------------
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small

# -------------------------
# Qdrant Vector Store Config
# -------------------------
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=enterprise_knowledge
# Automatically creates the collection if it doesn't exist
spring.ai.vectorstore.qdrant.initialize-schema=false

#COHERE Details
cohere.api.key=${COHERE_API_KEY}

# Keep your core app logging informative while silencing library-specific noise
logging.level.org.apache.pdfbox=WARN
logging.level.org.apache.fontbox=OFF

# Enable multipart uploads (default is true)
spring.servlet.multipart.enabled=true

# Maximum size permitted for a single uploaded file (Default is 1MB)
spring.servlet.multipart.max-file-size=15MB

# Maximum size allowed for a total multipart/form-data request (Default is 10MB)
spring.servlet.multipart.max-request-size=50MB

# Whether to resolve the multipart request lazily at the time of file/parameter access
spring.servlet.multipart.resolve-lazily=false

